### ISSUE TITLE
ZIP files on Google Drive

### ISSUE THREAD

**Issue by janzd** [chupibk/PoBDB_Patterns_of_Beauty#1]
I've downloaded the files from Google Drive but I cannot extract them. Is it possible that the files are somehow corrupted? It says the `Photograph.zip` file has 0 bytes, and the `Painting.zip` archive cannot be loaded.

**Comment by chupibk** [comment]
Thank you Jan for being interested in the dataset.

I'm on a holiday trip. I'll confirm the link as soon as I come back.

**Comment by chupibk** [comment]
@kurapan Sorry for the late reply. I've checked the links. 
Please download from here: 
	+ Paintings: https://drive.google.com/open?id=11wPfNtqJkenH401AqE38rD8OQMC1tcFa
	+ Photographs: https://drive.google.com/open?id=1sxFQz1Pb5T6lL_sZyAHmQzJmrlMlbZ1n

**Comment by janzd** [comment]
Thanks a lot! It's okay now.
